#define name "haxbox"
#define version "1.0.0"
#define wlook_updated "https://raw.github.com/aLibraryEnthusiast/haxbox/tf2_updated.txt"
#define wlook_true "1"
#define wlook_false "0"
#define haxbox_version "https://raw.github.com/aLibraryEnthusiast/haxbox/haxbox_version.txt"